import pandas as pd
import numpy as np


def load_csv_to_dict(csv_path):
    """Load pose and pen tip data from CSV file generated by freeaHandDrawing.py"""
    df = pd.read_csv(csv_path)

    data = {
        "frame": df["Frame"].astype(int),
        
        # Origin position (global coordinates in mm)
        "origin_x_mm": df["Origin_X_mm"].astype(float),
        "origin_y_mm": df["Origin_Y_mm"].astype(float),
        "origin_z_mm": df["Origin_Z_mm"].astype(float),
        
        # Rotation (Euler angles in degrees)
        "rotation_x_deg": df["Rotation_X_deg"].astype(float),
        "rotation_y_deg": df["Rotation_Y_deg"].astype(float),
        "rotation_z_deg": df["Rotation_Z_deg"].astype(float),
        
        # Pen tip position (3D global coordinates in mm)
        "pen_tip_x_mm": df["PenTip_Global_X_mm"].astype(float),
        "pen_tip_y_mm": df["PenTip_Global_Y_mm"].astype(float),
        "pen_tip_z_mm": df["PenTip_Global_Z_mm"].astype(float),
    }

    return data, df


def print_sample_data(data):
    """Print first few samples of the loaded data"""
    print("=" * 60)
    print("PEN TIP POSITION (first 5 frames):")
    print("=" * 60)
    print("Frame | Tip_X (mm) | Tip_Y (mm) | Tip_Z (mm)")
    print("-" * 60)
    for i in range(min(5, len(data["frame"]))):
        print(f"{data['frame'].iloc[i]:5d} | {data['pen_tip_x_mm'].iloc[i]:10.2f} | "
              f"{data['pen_tip_y_mm'].iloc[i]:10.2f} | {data['pen_tip_z_mm'].iloc[i]:10.2f}")
    
    print("\n" + "=" * 60)
    print("ROTATION (first 5 frames):")
    print("=" * 60)
    print("Frame | Rot_X (°) | Rot_Y (°) | Rot_Z (°)")
    print("-" * 60)
    for i in range(min(5, len(data["frame"]))):
        print(f"{data['frame'].iloc[i]:5d} | {data['rotation_x_deg'].iloc[i]:9.2f} | "
              f"{data['rotation_y_deg'].iloc[i]:9.2f} | {data['rotation_z_deg'].iloc[i]:9.2f}")
    
    print("\n" + "=" * 60)
    print("ORIGIN POSITION (first 5 frames):")
    print("=" * 60)
    print("Frame | Origin_X (mm) | Origin_Y (mm) | Origin_Z (mm)")
    print("-" * 60)
    for i in range(min(5, len(data["frame"]))):
        print(f"{data['frame'].iloc[i]:5d} | {data['origin_x_mm'].iloc[i]:13.2f} | "
              f"{data['origin_y_mm'].iloc[i]:13.2f} | {data['origin_z_mm'].iloc[i]:13.2f}")
    
    print("\n" + "=" * 60)
    print(f"Total frames loaded: {len(data['frame'])}")
    print("=" * 60)

import matplotlib.pyplot as plt

def plot_from_data_dict(data, every=1):
    x = data["pen_tip_x_mm"].to_numpy()[::every]
    y = data["pen_tip_y_mm"].to_numpy()[::every]
    z = data["pen_tip_z_mm"].to_numpy()[::every]

    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")
    ax.plot(x, y, z, linewidth=1)
    ax.set_xlabel("X (mm)")
    ax.set_ylabel("Y (mm)")
    ax.set_zlabel("Z (mm)")
    ax.set_title("Pen Tip 3D Trajectory (from dict)")
    ax.set_box_aspect([1, 1, 1])
    plt.show()


if __name__ == '__main__':
    # Load the CSV file
    csv_file = "pose_and_pen_tip_data.csv"
    
    try:
        data, df = load_csv_to_dict(csv_file)
        print_sample_data(data)
        
        # Additional statistics
        print("\nPEN TIP STATISTICS:")
        print(f"  X range: {data['pen_tip_x_mm'].min():.2f} to {data['pen_tip_x_mm'].max():.2f} mm")
        print(f"  Y range: {data['pen_tip_y_mm'].min():.2f} to {data['pen_tip_y_mm'].max():.2f} mm")
        print(f"  Z range: {data['pen_tip_z_mm'].min():.2f} to {data['pen_tip_z_mm'].max():.2f} mm")
        
    except FileNotFoundError:
        print(f"Error: File '{csv_file}' not found.")
        print("Make sure to run freeaHandDrawing.py and save the data first (press 's' or exit).")
    
    